name: my_music_player
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- 图标 ---
  cupertino_icons: ^1.0.8

  # --- 状态管理 ---
  flutter_riverpod: ^2.5.1

  # --- 播放器 (必须要有这两个) ---
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11  # <--- 核心依赖

  # --- 其他工具 ---
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # ⚠️ 资源路径配置 (只保留存在的文件夹)
  assets:
    - assets/audio/
    - assets/icons/
    - assets/scene/
    # - assets/images/  <-- 这一行删掉了，因为它不存在会导致崩溃
    # - assets/         <-- 这一行也建议删掉，除非你在 assets 根目录下直接放了文件

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/icon.png"